In [122]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
from tensorflow import keras
import numpy as np 

Class 1: 0-19

Class 2: 20-37

Class 3: 38-56

Class 4: 57-75

Class 5: 76-105

Class 6: 106 - 135

Class 7: 136-164

In [ ]:
from random import seed
from random import randint

seed(1)

with open("AllData.txt", "r") as f:
    data = []
    data = f.read()
    data = data.split("\n")

print(len(data))

with open("AllTestSet.txt", "w+") as f:
    for x in range(round(0.1*len(data))):

        # Random value
        value = randint(0,len(data))

        # Find list in data
        myList = data[value]

        # Remove list from data
        data.remove(myList)

        # Add the list 
        f.write(myList)
        f.write('\n')
        
with open("AllTrainingSet.txt", "w+") as f:
    for x in range(len(data)):
        f.write(data[x])
        f.write("\n")
        

# Checking Data 

with open("AllTestSet.txt", "r") as f:
    data = []
    data = f.read()
    data = data.split("\n")
    
print(len(data))

with open("AllTrainingSet.txt", "r") as f:
    data = []
    data = f.read()
    data = data.split("\n")
    
print(len(data))

The main reason why we use sigmoid function is because it exists between (0 to 1). 
Therefore, it is especially used for models where we have to predict the probability as an output. 
Since probability of anything exists only between the range of 0 and 1, sigmoid is the right choice. 
The function is differentiable.

In [123]:
with open ("AllTestSet.txt", "r") as f:
    data = []
    data = f.read()
    data = data.split("\n")
           
testArray = []
for y in range(0,len(data)):
    myList = []
    myList = data[y].split(",")
    for x in range(len(myList)-1):
        myList[x] = float(myList[x])
    
    # removes the '' at the end of each list
    myList = myList[1:len(myList)-1]
    testArray.append(myList)
    # convert the data set from a list of strings to a list of ints 

labelArray = []

for x in range(len(testArray)):
    if (testArray[x] != []):
        cls = testArray[x][len(testArray[x])-1]
        labelClass = []
        
        for y in range(0, 8):
            if(y == int(cls)):
                labelClass.append(1)
            else:
                labelClass.append(0)
        labelArray.append(labelClass)
        testArray[x].pop()

for x in range(len(testArray) - len(labelArray)):
    testArray.remove([])

testArray = np.asarray(testArray)
labelArray = np.asarray(labelArray)

print(testArray.shape)
print(labelArray.shape)
        
# Training Set

with open ("AllTrainingSet.txt", "r") as f:
    data = []
    data = f.read()
    data = data.split("\n")
           
trainingArray = []
for y in range(0,len(data)):
    myList = []
    myList = data[y].split(",")
    for x in range(len(myList)-1):
        myList[x] = float(myList[x])

    myList = myList[1:len(myList)-1]
    trainingArray.append(myList)
    # convert the data set from a list of strings to a list of ints 


trainLabArray = []

for x in range(len(trainingArray)-1):
    if (trainingArray[x] != []):
        cls = trainingArray[x][len(trainingArray[x])-1]
        labelClass = []
        
        for y in range(0, 8):
            if(y == int(cls)):
                labelClass.append(1)
            else:
                labelClass.append(0)
        trainLabArray.append(labelClass)
        trainingArray[x].pop()

for x in range(len(trainingArray) - len(trainLabArray)):
    trainingArray.remove([])

trainingArray = np.asarray(trainingArray)
trainLabArray = np.asarray(trainLabArray)
print(trainLabArray)
print(trainingArray)

print(trainingArray.shape)
print(trainLabArray.shape)


(1606, 56)
(1606, 8)
[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]
[[-5.17578125e-03  9.91410559e-02  1.88616943e+00 ...  8.96985018e-03
   1.74976312e+00  0.00000000e+00]
 [-6.05468750e-03  2.12881666e-02  5.92041016e-02 ...  3.23949886e-03
   1.74200501e+00  0.00000000e+00]
 [-5.95703125e-03  1.91565622e-02  4.72412109e-02 ...  1.97707550e-03
   1.56230509e+00  0.00000000e+00]
 ...
 [-4.78515625e-03  3.53402304e-02  1.61499023e-01 ...  1.34277344e-03
   1.60587242e+00  0.00000000e+00]
 [-2.83203125e-03  2.97106201e-02  1.33544922e-01 ...  1.20988677e-03
   1.64952875e+00  0.00000000e+00]
 [-1.95312500e-03  2.42376438e-02  7.30590820e-02 ...  1.16739394e-03
   1.60739522e+00  0.00000000e+00]]
(14427, 56)
(14427, 8)


In [124]:
from tensorflow.keras import layers

model = tf.keras.Sequential()

# Layer represents the number of inputs 
model.add(layers.Dense(56))

# activation layer connects each input node to all the neurons in the hidden layer
# Sigmoid is always before softmax (sigmoid = graph plateus)
model.add(layers.Dense(28, activation='sigmoid'))

# softmax layer essentially gives a probability value to each of the outputs (all add up to 1)
model.add(layers.Dense(8, activation='softmax'))

model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
    loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(trainingArray, trainLabArray, epochs=15, batch_size=56, validation_data=(testArray,labelArray))


Train on 14427 samples, validate on 1606 samples
Epoch 1/15
14427/14427 [==============================] - 1s 77us/sample - loss: 0.4620 - accuracy: 0.8761 - val_loss: 0.2576 - val_accuracy: 0.9278
Epoch 2/15
14427/14427 [==============================] - 1s 38us/sample - loss: 0.2501 - accuracy: 0.9281 - val_loss: 0.2513 - val_accuracy: 0.9197
Epoch 3/15
14427/14427 [==============================] - 1s 40us/sample - loss: 0.2457 - accuracy: 0.9282 - val_loss: 0.2299 - val_accuracy: 0.9296
Epoch 4/15
14427/14427 [==============================] - 1s 44us/sample - loss: 0.2314 - accuracy: 0.9321 - val_loss: 0.2315 - val_accuracy: 0.9346
Epoch 5/15
14427/14427 [==============================] - 1s 42us/sample - loss: 0.2220 - accuracy: 0.9356 - val_loss: 0.2605 - val_accuracy: 0.9147
Epoch 6/15
14427/14427 [==============================] - 1s 44us/sample - loss: 0.2301 - accuracy: 0.9335 - val_loss: 0.2209 - val_accuracy: 0.9384
Epoch 7/15
14427/14427 [==============================] -

In [131]:
with open ("AllData.txt", "r") as f:
    data = []
    data = f.read()
    data = data.split("\n")
           
testArray = []
for y in range(0,len(data)):
    myList = []
    myList = data[y].split(",")
    for x in range(len(myList)-1):
        myList[x] = float(myList[x])
    
    # removes the '' at the end of each list
    myList = myList[1:len(myList)-1]
    testArray.append(myList)
    # convert the data set from a list of strings to a list of ints 

labelArray = []

for x in range(len(testArray)):
    if (testArray[x] != []):
        cls = testArray[x][len(testArray[x])-1]
        labelClass = []
        
        for y in range(0, 8):
            if(y == int(cls)):
                labelClass.append(1)
            else:
                labelClass.append(0)
        labelArray.append(labelClass)
        testArray[x].pop()

for x in range(len(testArray) - len(labelArray)):
    testArray.remove([])

testArray = np.asarray(testArray)

print(len(testArray))
labelArray = np.asarray(labelArray)

58


In [130]:
predictions = model.predict(testArray)

print('predictions shape:', predictions)

predictions shape: [[8.69933283e-05 6.83128193e-04 1.82545659e-06 1.64387639e-05
  5.73887974e-07 8.73768926e-01 4.16829107e-06 1.25438064e-01]
 [1.58672119e-04 8.51560908e-04 1.48070842e-06 1.54511145e-05
  2.72232683e-07 8.86039555e-01 9.02356351e-06 1.12924039e-01]
 [2.13914886e-04 9.49798559e-04 1.33334481e-06 1.49728030e-05
  1.87663517e-07 8.91702831e-01 1.32488467e-05 1.07103772e-01]
 [2.16870976e-04 9.54575371e-04 1.32695152e-06 1.49513435e-05
  1.84485387e-07 8.91955435e-01 1.34845286e-05 1.06843069e-01]
 [2.16848770e-04 9.54530551e-04 1.32694731e-06 1.49509106e-05
  1.84498006e-07 8.91954303e-01 1.34831744e-05 1.06844462e-01]
 [2.16048982e-04 9.62932536e-04 1.32677951e-06 1.47877308e-05
  1.82166971e-07 8.90827477e-01 1.36863182e-05 1.07963480e-01]
 [1.96984649e-04 9.44913307e-04 1.36757717e-06 1.46840766e-05
  1.99219883e-07 8.87499392e-01 1.25114793e-05 1.11329988e-01]
 [1.94687309e-04 9.19928541e-04 1.37771065e-06 1.50807045e-05
  2.10143000e-07 8.89689207e-01 1.17941281e-