# Import libraries 

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
from random import random, seed

# Helper classes

In [57]:
class vectors_producer:
    def __init__(self, addresses):
        self.p = 0.1
        
        self.training_array = []
        self.training_labels = []
        self.validation_array = []
        self.validation_labels = []
        
        seed(1)
        
        # iterate through all of the files
        for i in range(len(addresses)):
            with open (addresses[i], 'r') as f:
                data = f.read()
             
            # iterate through features vectors
            data = data.split("\n")
            data.pop()
            
            # convert feature strings to lists
            for j in range(len(data)):
                data[j] = data[j].split(";")
                data[j].pop()                
                for k in range(len(data[j])):
                    data[j][k] = float(data[j][k])
                    
                if random() > self.p:
                    # append training set
                    if len(self.training_array) == 0: 
                        self.training_array = np.array([data[j][0:56]]) 
                        if data[j][56] == 0: self.training_labels = np.array([[1, 0, 0, 0, 0, 0, 0, 0]])
                        elif data[j][56] == 1: self.training_labels = np.array([[0, 1, 0, 0, 0, 0, 0, 0]])
                        elif data[j][56] == 2: self.training_labels = np.array([[0, 0, 1, 0, 0, 0, 0, 0]])
                        elif data[j][56] == 3: self.training_labels = np.array([[0, 0, 0, 1, 0, 0, 0, 0]])
                        elif data[j][56] == 4: self.training_labels = np.array([[0, 0, 0, 0, 1, 0, 0, 0]])
                        elif data[j][56] == 5: self.training_labels = np.array([[0, 0, 0, 0, 0, 1, 0, 0]])
                        elif data[j][56] == 6: self.training_labels = np.array([[0, 0, 0, 0, 0, 0, 1, 0]])
                        elif data[j][56] == 7: self.training_labels = np.array([[0, 0, 0, 0, 0, 0, 0, 1]])
                    else:
                        self.training_array = np.append(self.training_array, [data[j][0:56]], axis=0)
                        if data[j][56] == 0: self.training_labels = np.append(self.training_labels, [[1, 0, 0, 0, 0, 0, 0, 0]], axis=0)
                        elif data[j][56] == 1: self.training_labels = np.append(self.training_labels, [[0, 1, 0, 0, 0, 0, 0, 0]], axis=0)
                        elif data[j][56] == 2: self.training_labels = np.append(self.training_labels, [[0, 0, 1, 0, 0, 0, 0, 0]], axis=0)
                        elif data[j][56] == 3: self.training_labels = np.append(self.training_labels, [[0, 0, 0, 1, 0, 0, 0, 0]], axis=0)
                        elif data[j][56] == 4: self.training_labels = np.append(self.training_labels, [[0, 0, 0, 0, 1, 0, 0, 0]], axis=0)
                        elif data[j][56] == 5: self.training_labels = np.append(self.training_labels, [[0, 0, 0, 0, 0, 1, 0, 0]], axis=0)
                        elif data[j][56] == 6: self.training_labels = np.append(self.training_labels, [[0, 0, 0, 0, 0, 0, 1, 0]], axis=0)
                        elif data[j][56] == 7: self.training_labels = np.append(self.training_labels, [[0, 0, 0, 0, 0, 0, 0, 1]], axis=0)
                        
                else:
                    # append validation set
                    if len(self.validation_array) == 0: 
                        self.validation_array = np.array([data[j][0:56]]) 
                        if data[j][56] == 0: self.validation_labels = np.array([[1, 0, 0, 0, 0, 0, 0, 0]])
                        elif data[j][56] == 1: self.validation_labels = np.array([[0, 1, 0, 0, 0, 0, 0, 0]])
                        elif data[j][56] == 2: self.validation_labels = np.array([[0, 0, 1, 0, 0, 0, 0, 0]])
                        elif data[j][56] == 3: self.validation_labels = np.array([[0, 0, 0, 1, 0, 0, 0, 0]])
                        elif data[j][56] == 4: self.validation_labels = np.array([[0, 0, 0, 0, 1, 0, 0, 0]])
                        elif data[j][56] == 5: self.validation_labels = np.array([[0, 0, 0, 0, 0, 1, 0, 0]])
                        elif data[j][56] == 6: self.validation_labels = np.array([[0, 0, 0, 0, 0, 0, 1, 0]])
                        elif data[j][56] == 7: self.validation_labels = np.array([[0, 0, 0, 0, 0, 0, 0, 1]])
                    else:
                        self.validation_array = np.append(self.validation_array, [data[j][0:56]], axis=0)
                        if data[j][56] == 0: self.validation_labels = np.append(self.validation_labels, [[1, 0, 0, 0, 0, 0, 0, 0]], axis=0)
                        elif data[j][56] == 1: self.validation_labels = np.append(self.validation_labels, [[0, 1, 0, 0, 0, 0, 0, 0]], axis=0)
                        elif data[j][56] == 2: self.validation_labels = np.append(self.validation_labels, [[0, 0, 1, 0, 0, 0, 0, 0]], axis=0)
                        elif data[j][56] == 3: self.validation_labels = np.append(self.validation_labels, [[0, 0, 0, 1, 0, 0, 0, 0]], axis=0)
                        elif data[j][56] == 4: self.validation_labels = np.append(self.validation_labels, [[0, 0, 0, 0, 1, 0, 0, 0]], axis=0)
                        elif data[j][56] == 5: self.validation_labels = np.append(self.validation_labels, [[0, 0, 0, 0, 0, 1, 0, 0]], axis=0)
                        elif data[j][56] == 6: self.validation_labels = np.append(self.validation_labels, [[0, 0, 0, 0, 0, 0, 1, 0]], axis=0)
                        elif data[j][56] == 7: self.validation_labels = np.append(self.validation_labels, [[0, 0, 0, 0, 0, 0, 0, 1]], axis=0)
                            

# Addresses

In [58]:
directory = {
    "noise": "data/raw_data/noise/noise_reference 1.txt",

    "noise taps 1 features 1": "data/features1/noise/taps_noise 1.txt",
    "noise taps 2 features 1": "data/features1/noise/taps_noise 2.txt",
    "noise taps 3 features 1": "data/features1/noise/taps_noise 3.txt",
    "noise taps 4 features 1": "data/features1/noise/taps_noise 4.txt",

    "noise taps 4 features 2": "data/features2/noise/taps_noise 4.txt",
    "noise taps 4 features 3": "data/features3/noise/taps_noise 4.txt",
    "noise taps 4 features 4": "data/features4/noise/taps_noise 4.txt",
    
    
    # features 4 data
    "A_features4": "data/features4/taps 2/A/",
    "D_alt_features4": "data/features4/taps 2/D alt/",
    "S_features4": "data/features4/taps 2/S/",
    "F_features4": "data/features4/taps 2/F/",

    
    # features 3 data
    "A_features3": "data/features3/taps 2/A/",
    "D_alt_features3": "data/features3/taps 2/D alt/",
    "S_features3": "data/features3/taps 2/S/",
    "F_features3": "data/features3/taps 2/F/",

    
    # features 2 data
    "A_features2": "data/features2/taps 2/A/",
    "D_alt_features2": "data/features2/taps 2/D alt/",
    "S_features2": "data/features2/taps 2/S/",
    "F_features2": "data/features2/taps 2/F/",

    
    # features 1 data
    "index_finger_features1": "data/features1/taps/index_finger/",
    "middle_finger_features1": "data/features1/taps/middle_finger/",
    "ring_finger_features1": "data/features1/taps/ring_finger/",
    "little_finger_features1": "data/features1/taps/little_finger/",
    
    "hand_up_features1": "data/features1/hand_movement/up/",
    "hand_down_features1": "data/features1/hand_movement/down/",
    "hand_left_features1": "data/features1/hand_movement/left/",
    "hand_right_features1": "data/features1/hand_movement/right/",
    
    "A_features1": "data/features1/taps 2/A/",
    "D_features1": "data/features1/taps 2/D/",
    "D_alt_features1": "data/features1/taps 2/D alt/",
    "E_features1": "data/features1/taps 2/E/",
    "E_new_features1": "data/features1/taps 2/E new/",
    "F_features1": "data/features1/taps 2/F/",
    "R_features1": "data/features1/taps 2/R/",
    "R_new_features1": "data/features1/taps 2/R new/",
    "S_features1": "data/features1/taps 2/S/",
    "W_features1": "data/features1/taps 2/W/",
    "W_new_features1": "data/features1/taps 2/W new/"
}

# Neural Network

In [61]:
# init and compile NN network

model = tf.keras.Sequential()
model.add(layers.Dense(56))
model.add(layers.Dense(28, activation='sigmoid'))
model.add(layers.Dense(8, activation='softmax'))

model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [59]:
input_file_list = []

for i in range(1, 61):
    if not (i == 5):
        input_file = directory["A_features1"] + "A" + str(i) + ", features.txt"
        input_file_list.append(input_file)

    
for i in range(1, 61):
    input_file = directory["S_features1"] + "S" + str(i) + ", features.txt"
    input_file_list.append(input_file)
    
    
for i in range(1, 121):
    input_file = directory["D_alt_features1"] + "D" + str(i) + " alt, features.txt"
    input_file_list.append(input_file)    
        
    
for i in range(1, 61):
    input_file = directory["F_features1"] + "F" + str(i) + ", features.txt"
    input_file_list.append(input_file)

    
for i in range(1, 31):
    input_file = directory["W_features1"] + "W" + str(i) + ", features.txt"
    input_file_list.append(input_file)

    
for i in range(1, 31):
    if not (i == 26):
        input_file = directory["E_features1"] + "E" + str(i) + ", features.txt"
        input_file_list.append(input_file)

    
for i in range(1, 31):
    input_file = directory["R_features1"] + "R" + str(i) + ", features.txt"
    input_file_list.append(input_file)

    
input_file_list.append(directory["noise taps 4 features 1"])

mvectors_producer = vectors_producer(input_file_list)
print(mvectors_producer.training_array.shape)
print(mvectors_producer.training_labels.shape)
print(mvectors_producer.validation_array.shape)
print(mvectors_producer.validation_labels.shape)

(23048, 56)
(23048, 8)
(2656, 56)
(2656, 8)


In [62]:
data = mvectors_producer.training_array
labels = mvectors_producer.training_labels
val_data = mvectors_producer.validation_array
val_labels = mvectors_producer.validation_labels

# train NN network
model.fit(data, labels, epochs=10, batch_size=32,
          validation_data=(val_data, val_labels))

Train on 23048 samples, validate on 2656 samples
Epoch 1/10
23048/23048 [==============================] - 1s 47us/sample - loss: 0.3597 - accuracy: 0.8740 - val_loss: 0.2761 - val_accuracy: 0.8919
Epoch 2/10
23048/23048 [==============================] - 1s 33us/sample - loss: 0.2309 - accuracy: 0.9101 - val_loss: 0.2425 - val_accuracy: 0.9059
Epoch 3/10
23048/23048 [==============================] - 1s 34us/sample - loss: 0.2191 - accuracy: 0.9174 - val_loss: 0.2546 - val_accuracy: 0.9044
Epoch 4/10
23048/23048 [==============================] - 1s 34us/sample - loss: 0.2199 - accuracy: 0.9171 - val_loss: 0.2327 - val_accuracy: 0.9160
Epoch 5/10
23048/23048 [==============================] - 1s 37us/sample - loss: 0.2212 - accuracy: 0.9171 - val_loss: 0.2415 - val_accuracy: 0.9115
Epoch 6/10
23048/23048 [==============================] - 1s 38us/sample - loss: 0.2071 - accuracy: 0.9223 - val_loss: 0.2565 - val_accuracy: 0.9044
Epoch 7/10
23048/23048 [==============================] -

In [63]:
# Export the model to a SavedModel
model.save('./models/asdf_wer', save_format='tf')

INFO:tensorflow:Assets written to: ./models/asdf_wer\assets


In [64]:
converter = tf.lite.TFLiteConverter.from_saved_model('./models/asdf_wer')
tflite_model = converter.convert()
open("asdf_wer.tflite", "wb").write(tflite_model)

22096

In [ ]:
l = np.array([[0.008208069620253165,0.13515364904755717,2.358642578125,12.5625,0.018500694861778844,1.5442547558352973,0,-0.005636867088607595,0.06604021186121416,0.798095703125,5.71875,0.004417223808092949,1.7193732765538572,0,-0.006625791139240506,0.019713352024000177,0.039794921875,1.34375,0.0003935985076121795,1.4489318750475562,0,-0.0038568037974683546,0.0548144999129977,0.3221435546875,4.171875,0.0030431502904647435,1.4232756412731158,0,-0.005340189873417721,0.027628350504188236,0.082275390625,2.15625,0.0007731119791666666,1.3911228098427462,0,-0.007416930379746835,0.05043968318334361,0.34173583984375,3.7734375,0.002576779096554487,1.5342036198103477,0,-0.008999208860759493,0.04011632302470095,0.1951904296875,3.34375,0.001629951672676282,1.4850834574730492,0,-0.007021360759493671,0.03988454646943832,0.1619873046875,3.15625,0.001611171624599359,1.3581549064368843,0]])
#print(l)
model.predict(l)

In [70]:
y_pred=model.predict_classes(val_data)

y_label = np.zeros(len(y_pred))
for i in range(len(y_pred)):
    if val_labels[i][1] == 1: y_label[i] = 1
    elif val_labels[i][2] == 1: y_label[i] = 2
    elif val_labels[i][3] == 1: y_label[i] = 3
    elif val_labels[i][4] == 1: y_label[i] = 4
    elif val_labels[i][5] == 1: y_label[i] = 5
    elif val_labels[i][6] == 1: y_label[i] = 6
    elif val_labels[i][7] == 1: y_label[i] = 7
        

con_mat = tf.math.confusion_matrix(labels=y_label, predictions=y_pred).numpy()
con_mat_norm = np.around(con_mat.astype('float') / con_mat.sum(axis=1)[:, np.newaxis], decimals=2)    

print(con_mat)

[[1142    6   94    5   10    0    3    3]
 [   0  170    0    3    0   12    2    5]
 [  16    0  290    0    0    0    5    0]
 [   1    0    0  268    0    0    0   11]
 [  10    0    0    0  202    0    0    0]
 [   0   18    0    0    0  127    0    0]
 [   7    1    6    1    6    1   82    1]
 [   7    3    0   23    0    1    5  109]]
